<?php

/**
 * Generated by Sterling SDK Generator — test suite
 * Orchestrator Control Plane API v0.1.0
 *
 * Tests for VersSdkClient — verifies URL construction, HTTP methods, and error handling.
 */

declare(strict_types=1);

namespace VersSdk\Tests;

use PHPUnit\Framework\TestCase;

// Include source files directly for testing without Composer autoload
require_once __DIR__ . '/../src/Errors.php';
require_once __DIR__ . '/../src/Models.php';
require_once __DIR__ . '/../src/Client.php';

use VersSdk\VersSdkClient;
use VersSdk\ApiException;
use VersSdk\BadRequestException;
use VersSdk\NotFoundException;
use VersSdk\InternalServerException;

class ClientTest extends TestCase
{
    private function makeClient(): VersSdkClient
    {
        return new VersSdkClient(
            baseUrl: 'http://localhost:9999',
            apiKey: 'test-key',
            maxRetries: 0,
        );
    }

    /**
     * Verify the client can be instantiated.
     */
    public function testClientConstruction(): void
    {
        $client = $this->makeClient();
        $this->assertInstanceOf(VersSdkClient::class, $client);
    }

    /**
     * Verify that ApiException::generate creates proper exception subclasses.
     */
    public function testErrorGenerate400(): void
    {
        $this->expectException(BadRequestException::class);
        throw ApiException::generate(400, ['message' => 'bad request'], null, []);
    }

    public function testErrorGenerate404(): void
    {
        $this->expectException(NotFoundException::class);
        throw ApiException::generate(404, ['message' => 'not found'], null, []);
    }

    public function testErrorGenerate500(): void
    {
        $this->expectException(InternalServerException::class);
        throw ApiException::generate(500, ['message' => 'server error'], null, []);
    }

    /**
     * Test that the vmLogs method exists and is callable.
     */
    public function testMethodExists_vmLogs(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'vmLogs'));
    }

    public function testMethodExists_upsertVmLabels(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'upsertVmLabels'));
    }

    public function testMethodExists_listPublicRepoTags(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listPublicRepoTags'));
    }

    public function testMethodExists_listParentCommits(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listParentCommits'));
    }

    public function testMethodExists_updateVmState(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'updateVmState'));
    }

    public function testMethodExists_listRepositories(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listRepositories'));
    }

    public function testMethodExists_createRepository(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'createRepository'));
    }

    public function testMethodExists_getPublicRepoTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'getPublicRepoTag'));
    }

    public function testMethodExists_listTags(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listTags'));
    }

    public function testMethodExists_createTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'createTag'));
    }

    public function testMethodExists_listVms(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listVms'));
    }

    public function testMethodExists_getVmMetadata(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'getVmMetadata'));
    }

    public function testMethodExists_listCommits(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listCommits'));
    }

    public function testMethodExists_listRepoTags(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listRepoTags'));
    }

    public function testMethodExists_createRepoTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'createRepoTag'));
    }

    public function testMethodExists_execVm(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'execVm'));
    }

    public function testMethodExists_setRepositoryVisibility(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'setRepositoryVisibility'));
    }

    public function testMethodExists_listImages(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listImages'));
    }

    public function testMethodExists_readFileVm(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'readFileVm'));
    }

    public function testMethodExists_writeFileVm(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'writeFileVm'));
    }

    public function testMethodExists_getPublicRepository(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'getPublicRepository'));
    }

    public function testMethodExists_resizeVmDisk(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'resizeVmDisk'));
    }

    public function testMethodExists_execVmStreamAttach(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'execVmStreamAttach'));
    }

    public function testMethodExists_createNewRootVm(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'createNewRootVm'));
    }

    public function testMethodExists_branchByRef(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'branchByRef'));
    }

    public function testMethodExists_replaceVmLabels(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'replaceVmLabels'));
    }

    public function testMethodExists_listPublicCommits(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listPublicCommits'));
    }

    public function testMethodExists_getImageStatus(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'getImageStatus'));
    }

    public function testMethodExists_versionHandler(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'versionHandler'));
    }

    public function testMethodExists_branchByTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'branchByTag'));
    }

    public function testMethodExists_getRepoTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'getRepoTag'));
    }

    public function testMethodExists_deleteRepoTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteRepoTag'));
    }

    public function testMethodExists_updateRepoTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'updateRepoTag'));
    }

    public function testMethodExists_branchVm(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'branchVm'));
    }

    public function testMethodExists_getRepository(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'getRepository'));
    }

    public function testMethodExists_deleteRepository(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteRepository'));
    }

    public function testMethodExists_validateKey(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'validateKey'));
    }

    public function testMethodExists_forkRepository(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'forkRepository'));
    }

    public function testMethodExists_deleteVmLabel(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteVmLabel'));
    }

    public function testMethodExists_createImage(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'createImage'));
    }

    public function testMethodExists_restoreFromCommit(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'restoreFromCommit'));
    }

    public function testMethodExists_getDomain(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'getDomain'));
    }

    public function testMethodExists_deleteDomain(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteDomain'));
    }

    public function testMethodExists_listPublicRepositories(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listPublicRepositories'));
    }

    public function testMethodExists_listEnvVars(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listEnvVars'));
    }

    public function testMethodExists_setEnvVars(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'setEnvVars'));
    }

    public function testMethodExists_deleteVm(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteVm'));
    }

    public function testMethodExists_getTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'getTag'));
    }

    public function testMethodExists_deleteTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteTag'));
    }

    public function testMethodExists_updateTag(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'updateTag'));
    }

    public function testMethodExists_branchByVm(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'branchByVm'));
    }

    public function testMethodExists_deleteEnvVar(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteEnvVar'));
    }

    public function testMethodExists_deleteImage(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteImage'));
    }

    public function testMethodExists_commitVm(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'commitVm'));
    }

    public function testMethodExists_deleteCommit(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deleteCommit'));
    }

    public function testMethodExists_updateCommit(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'updateCommit'));
    }

    public function testMethodExists_execVmStream(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'execVmStream'));
    }

    public function testMethodExists_deployHandler(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'deployHandler'));
    }

    public function testMethodExists_sshKey(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'sshKey'));
    }

    public function testMethodExists_vmStatus(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'vmStatus'));
    }

    public function testMethodExists_listDomains(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'listDomains'));
    }

    public function testMethodExists_createDomain(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'createDomain'));
    }

    public function testMethodExists_whoamiHandler(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'whoamiHandler'));
    }

    public function testMethodExists_uploadImage(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'uploadImage'));
    }

    public function testMethodExists_branchByCommit(): void
    {
        $client = $this->makeClient();
        $this->assertTrue(method_exists($client, 'branchByCommit'));
    }

}
