<?php

/**
 * Generated by Sterling SDK Generator
 * Orchestrator Control Plane API v0.1.0
 */

declare(strict_types=1);

namespace VersSdk;

class RequestOptions
{
    /**
     * @param array<string, string|null>|null $headers Additional headers (null value removes header)
     * @param float|null $timeout Request timeout in seconds
     */
    public function __construct(
        public readonly ?array $headers = null,
        public readonly ?float $timeout = null,
    ) {}
}

class VersSdkClient
{
    private string $baseUrl;
    private ?string $apiKey;
    private int $maxRetries;
    private float $timeout;
    /** @var array<string, string> */
    private array $defaultHeaders;

    private const RETRYABLE_STATUS_CODES = [408, 409, 429];

    public function __construct(
        ?string $baseUrl = null,
        ?string $apiKey = null,
        int $maxRetries = 2,
        float $timeout = 30.0,
    ) {
        $this->baseUrl = $baseUrl ?? ($_ENV['VERS_BASE_URL'] ?? 'https://api.vers.sh');
        $this->apiKey = $apiKey ?? ($_ENV['VERS_API_KEY'] ?? null);
        $this->maxRetries = $maxRetries;
        $this->timeout = $timeout;

        $this->defaultHeaders = [
            'Content-Type' => 'application/json',
            'Accept' => 'application/json',
            'User-Agent' => 'vers-sdk/0.1.8 php/' . PHP_VERSION,
        ];
        if ($this->apiKey !== null) {
            $this->defaultHeaders['Authorization'] = 'Bearer ' . $this->apiKey;
        }
    }

    /**
     * Merge header arrays. Later sources override earlier (case-insensitive).
     * A null value removes the header.
     *
     * @param array<string, string|null> ...$sources
     * @return array<string, string>
     */
    private function mergeHeaders(array ...$sources): array
    {
        $merged = [];
        foreach ($sources as $source) {
            foreach ($source as $key => $value) {
                if ($value === null) {
                    foreach ($merged as $k => $_) {
                        if (strcasecmp($k, $key) === 0) {
                            unset($merged[$k]);
                        }
                    }
                } else {
                    $merged[$key] = $value;
                }
            }
        }
        return $merged;
    }

    /**
     * Calculate retry delay with exponential backoff and jitter.
     */
    private function retryDelay(int $attempt): float
    {
        $base = 0.5 * (2 ** $attempt);
        $jitter = (mt_rand() / mt_getrandmax()) * $base * 0.25;
        return $base + $jitter;
    }

    /**
     * Parse Retry-After header value.
     */
    private function parseRetryAfter(?string $value): ?float
    {
        if ($value === null) {
            return null;
        }
        if (is_numeric($value)) {
            $delay = (float) $value;
            return min(max($delay, 0.0), 60.0);
        }
        $timestamp = strtotime($value);
        if ($timestamp !== false) {
            $delay = (float) ($timestamp - time());
            return min(max($delay, 0.0), 60.0);
        }
        return null;
    }

    /**
     * Check if a status code is retryable.
     */
    private function isRetryableStatus(int $status): bool
    {
        return $status >= 500 || in_array($status, self::RETRYABLE_STATUS_CODES, true);
    }

    /**
     * Check response and throw appropriate exception on error.
     *
     * @param array<string, string> $responseHeaders
     * @throws ApiException
     */
    private function checkResponse(int $statusCode, string $body, array $responseHeaders): void
    {
        if ($statusCode >= 200 && $statusCode < 300) {
            return;
        }
        $ct = $responseHeaders['content-type'] ?? $responseHeaders['Content-Type'] ?? '';
        $decoded = null;
        $message = null;
        if (str_contains($ct, 'application/json')) {
            $decoded = json_decode($body, true);
            if (is_array($decoded) && isset($decoded['message'])) {
                $message = (string) $decoded['message'];
            } elseif (!is_array($decoded)) {
                $message = $body;
                $decoded = null;
            }
        } else {
            $message = $body;
        }
        throw ApiException::generate($statusCode, $decoded, $message, $responseHeaders);
    }

    /**
     * Perform an HTTP request with retry logic.
     *
     * @param array<string, mixed> $options
     * @return array{status: int, headers: array<string, string>, body: string, decoded: mixed}
     * @throws ApiException
     * @throws ApiConnectionException
     */
    private function request(
        string $method,
        string $path,
        ?RequestOptions $requestOptions = null,
        ?array $body = null,
        ?array $query = null,
    ): array {
        $url = rtrim($this->baseUrl, '/') . $path;
        if ($query !== null && count($query) > 0) {
            $url .= '?' . http_build_query($query);
        }

        $reqHeaders = $this->defaultHeaders;

        // Idempotency key for mutating methods
        $upperMethod = strtoupper($method);
        if (in_array($upperMethod, ['POST', 'PUT', 'PATCH', 'DELETE'], true)) {
            $reqHeaders['X-Idempotency-Key'] = $this->generateUuid();
        }

        // Apply per-request header overrides
        if ($requestOptions !== null && $requestOptions->headers !== null) {
            $reqHeaders = $this->mergeHeaders($reqHeaders, $requestOptions->headers);
        }

        $effectiveTimeout = ($requestOptions !== null && $requestOptions->timeout !== null)
            ? $requestOptions->timeout
            : $this->timeout;

        $lastException = null;
        $retryAfterUsed = false;

        for ($attempt = 0; $attempt <= $this->maxRetries; $attempt++) {
            if ($attempt > 0 && !$retryAfterUsed) {
                usleep((int) ($this->retryDelay($attempt - 1) * 1_000_000));
            }
            $retryAfterUsed = false;

            try {
                $ch = curl_init();
                if ($ch === false) {
                    throw new ApiConnectionException('Failed to initialize cURL');
                }

                curl_setopt_array($ch, [
                    CURLOPT_URL => $url,
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_HEADER => true,
                    CURLOPT_TIMEOUT => (int) ceil($effectiveTimeout),
                    CURLOPT_CONNECTTIMEOUT => 10,
                    CURLOPT_CUSTOMREQUEST => $upperMethod,
                ]);

                // Set headers
                $headerLines = [];
                foreach ($reqHeaders as $k => $v) {
                    $headerLines[] = "$k: $v";
                }
                curl_setopt($ch, CURLOPT_HTTPHEADER, $headerLines);

                // Set body
                if ($body !== null) {
                    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($body));
                }

                $response = curl_exec($ch);
                if ($response === false) {
                    $error = curl_error($ch);
                    curl_close($ch);
                    throw new ApiConnectionException("cURL error: $error");
                }

                $httpCode = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
                $headerSize = (int) curl_getinfo($ch, CURLINFO_HEADER_SIZE);
                curl_close($ch);

                $rawHeaders = substr((string) $response, 0, $headerSize);
                $responseBody = substr((string) $response, $headerSize);
                $responseHeaders = $this->parseResponseHeaders($rawHeaders);

                // Check if retryable
                if ($this->isRetryableStatus($httpCode) && $attempt < $this->maxRetries) {
                    $raDelay = $this->parseRetryAfter($responseHeaders['retry-after'] ?? null);
                    if ($raDelay !== null) {
                        $retryAfterUsed = true;
                        usleep((int) ($raDelay * 1_000_000));
                    }
                    $lastException = new \RuntimeException("HTTP $httpCode");
                    continue;
                }

                $this->checkResponse($httpCode, $responseBody, $responseHeaders);

                return [
                    'status' => $httpCode,
                    'headers' => $responseHeaders,
                    'body' => $responseBody,
                    'decoded' => json_decode($responseBody, true),
                ];
            } catch (ApiException $e) {
                throw $e;
            } catch (\Throwable $e) {
                if ($attempt === $this->maxRetries) {
                    throw new ApiConnectionException($e->getMessage(), 0, $e);
                }
                $lastException = $e;
            }
        }

        throw $lastException ?? new ApiConnectionException('Request failed');
    }

    /**
     * Parse raw HTTP response headers into an associative array.
     *
     * @return array<string, string>
     */
    private function parseResponseHeaders(string $raw): array
    {
        $headers = [];
        foreach (explode("\r\n", $raw) as $line) {
            $parts = explode(':', $line, 2);
            if (count($parts) === 2) {
                $headers[strtolower(trim($parts[0]))] = trim($parts[1]);
            }
        }
        return $headers;
    }

    /**
     * Generate a UUID v4.
     */
    private function generateUuid(): string
    {
        $data = random_bytes(16);
        $data[6] = chr(ord($data[6]) & 0x0f | 0x40);
        $data[8] = chr(ord($data[8]) & 0x3f | 0x80);
        return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
    }

    // ── API Operations ──────────────────────────────────────────────────

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function vmStatus(string $vm_id, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/status', $vm_id);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param ResizeVmDiskParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function resizeVmDisk(string $vm_id, ?array $body = null, ?ResizeVmDiskParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/disk', $vm_id);
        $query = [];
        if ($params !== null) {
            if ($params->skip_wait_boot !== null) {
                $query['skip_wait_boot'] = is_bool($params->skip_wait_boot) ? ($params->skip_wait_boot ? 'true' : 'false') : $params->skip_wait_boot;
            }
        }
        $result = $this->request('PATCH', $path, $options, $body, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function execVmStreamAttach(string $vm_id, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/exec/stream/attach', $vm_id);
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listVms(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/vms';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param CreateNewRootVmParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function createNewRootVm(?array $body = null, ?CreateNewRootVmParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/vm/new_root';
        $query = [];
        if ($params !== null) {
            if ($params->wait_boot !== null) {
                $query['wait_boot'] = is_bool($params->wait_boot) ? ($params->wait_boot ? 'true' : 'false') : $params->wait_boot;
            }
        }
        $result = $this->request('POST', $path, $options, $body, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param VmLogsParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function vmLogs(string $vm_id, ?VmLogsParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/logs', $vm_id);
        $query = [];
        if ($params !== null) {
            if ($params->offset !== null) {
                $query['offset'] = is_bool($params->offset) ? ($params->offset ? 'true' : 'false') : $params->offset;
            }
            if ($params->max_entries !== null) {
                $query['max_entries'] = is_bool($params->max_entries) ? ($params->max_entries ? 'true' : 'false') : $params->max_entries;
            }
            if ($params->stream !== null) {
                $query['stream'] = is_bool($params->stream) ? ($params->stream ? 'true' : 'false') : $params->stream;
            }
        }
        $result = $this->request('GET', $path, $options, null, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param BranchByRefParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function branchByRef(string $repo_name, string $tag_name, ?array $body = null, ?BranchByRefParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/branch/by_ref/%s/%s', $repo_name, $tag_name);
        $query = [];
        if ($params !== null) {
            if ($params->count !== null) {
                $query['count'] = is_bool($params->count) ? ($params->count ? 'true' : 'false') : $params->count;
            }
        }
        $result = $this->request('POST', $path, $options, $body, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function labelVm(string $vm_id, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/label', $vm_id);
        $result = $this->request('PATCH', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listPublicCommits(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/commits/public';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function getImageStatus(string $image_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/images/%s/status', $image_name);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listPublicRepoTags(string $org_name, string $repo_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/public/repositories/%s/%s/tags', $org_name, $repo_name);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function versionHandler(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/system/version';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param BranchByTagParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function branchByTag(string $tag_name, ?array $body = null, ?BranchByTagParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/branch/by_tag/%s', $tag_name);
        $query = [];
        if ($params !== null) {
            if ($params->count !== null) {
                $query['count'] = is_bool($params->count) ? ($params->count ? 'true' : 'false') : $params->count;
            }
        }
        $result = $this->request('POST', $path, $options, $body, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function getRepoTag(string $repo_name, string $tag_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/repositories/%s/tags/%s', $repo_name, $tag_name);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deleteRepoTag(string $repo_name, string $tag_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/repositories/%s/tags/%s', $repo_name, $tag_name);
        $result = $this->request('DELETE', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function updateRepoTag(string $repo_name, string $tag_name, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/repositories/%s/tags/%s', $repo_name, $tag_name);
        $result = $this->request('PATCH', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param BranchVmParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function branchVm(string $vm_or_commit_id, ?array $body = null, ?BranchVmParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/branch', $vm_or_commit_id);
        $query = [];
        if ($params !== null) {
            if ($params->keep_paused !== null) {
                $query['keep_paused'] = is_bool($params->keep_paused) ? ($params->keep_paused ? 'true' : 'false') : $params->keep_paused;
            }
            if ($params->skip_wait_boot !== null) {
                $query['skip_wait_boot'] = is_bool($params->skip_wait_boot) ? ($params->skip_wait_boot ? 'true' : 'false') : $params->skip_wait_boot;
            }
            if ($params->count !== null) {
                $query['count'] = is_bool($params->count) ? ($params->count ? 'true' : 'false') : $params->count;
            }
        }
        $result = $this->request('POST', $path, $options, $body, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function getRepository(string $repo_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/repositories/%s', $repo_name);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deleteRepository(string $repo_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/repositories/%s', $repo_name);
        $result = $this->request('DELETE', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listParentCommits(string $commit_id, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/commits/%s/parents', $commit_id);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function validateKey(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/keys/validate';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function forkRepository(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/repositories/fork';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listRepositories(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/repositories';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function createRepository(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/repositories';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param UpdateVmStateParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function updateVmState(string $vm_id, ?array $body = null, ?UpdateVmStateParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/state', $vm_id);
        $query = [];
        if ($params !== null) {
            if ($params->skip_wait_boot !== null) {
                $query['skip_wait_boot'] = is_bool($params->skip_wait_boot) ? ($params->skip_wait_boot ? 'true' : 'false') : $params->skip_wait_boot;
            }
        }
        $result = $this->request('PATCH', $path, $options, $body, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function createImage(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/images/create';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function restoreFromCommit(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/vm/from_commit';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function getDomain(string $domain_id, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/domains/%s', $domain_id);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deleteDomain(string $domain_id, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/domains/%s', $domain_id);
        $result = $this->request('DELETE', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listTags(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/commit_tags';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function createTag(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/commit_tags';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listPublicRepositories(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/public/repositories';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function getPublicRepoTag(string $org_name, string $repo_name, string $tag_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/public/repositories/%s/%s/tags/%s', $org_name, $repo_name, $tag_name);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function getVmMetadata(string $vm_id, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/metadata', $vm_id);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listEnvVars(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/env_vars';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function setEnvVars(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/env_vars';
        $result = $this->request('PUT', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param DeleteVmParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deleteVm(string $vm_id, ?DeleteVmParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s', $vm_id);
        $query = [];
        if ($params !== null) {
            if ($params->skip_wait_boot !== null) {
                $query['skip_wait_boot'] = is_bool($params->skip_wait_boot) ? ($params->skip_wait_boot ? 'true' : 'false') : $params->skip_wait_boot;
            }
        }
        $result = $this->request('DELETE', $path, $options, null, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listCommits(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/commits';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function getTag(string $tag_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/commit_tags/%s', $tag_name);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deleteTag(string $tag_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/commit_tags/%s', $tag_name);
        $result = $this->request('DELETE', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function updateTag(string $tag_name, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/commit_tags/%s', $tag_name);
        $result = $this->request('PATCH', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param BranchByVmParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function branchByVm(string $vm_id, ?array $body = null, ?BranchByVmParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/branch/by_vm/%s', $vm_id);
        $query = [];
        if ($params !== null) {
            if ($params->keep_paused !== null) {
                $query['keep_paused'] = is_bool($params->keep_paused) ? ($params->keep_paused ? 'true' : 'false') : $params->keep_paused;
            }
            if ($params->skip_wait_boot !== null) {
                $query['skip_wait_boot'] = is_bool($params->skip_wait_boot) ? ($params->skip_wait_boot ? 'true' : 'false') : $params->skip_wait_boot;
            }
            if ($params->count !== null) {
                $query['count'] = is_bool($params->count) ? ($params->count ? 'true' : 'false') : $params->count;
            }
        }
        $result = $this->request('POST', $path, $options, $body, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deleteEnvVar(string $key, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/env_vars/%s', $key);
        $result = $this->request('DELETE', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deleteImage(string $base_image_id, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/images/images/%s', $base_image_id);
        $result = $this->request('DELETE', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param CommitVmParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function commitVm(string $vm_id, ?array $body = null, ?CommitVmParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/commit', $vm_id);
        $query = [];
        if ($params !== null) {
            if ($params->keep_paused !== null) {
                $query['keep_paused'] = is_bool($params->keep_paused) ? ($params->keep_paused ? 'true' : 'false') : $params->keep_paused;
            }
            if ($params->skip_wait_boot !== null) {
                $query['skip_wait_boot'] = is_bool($params->skip_wait_boot) ? ($params->skip_wait_boot ? 'true' : 'false') : $params->skip_wait_boot;
            }
        }
        $result = $this->request('POST', $path, $options, $body, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deleteCommit(string $commit_id, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/commits/%s', $commit_id);
        $result = $this->request('DELETE', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function updateCommit(string $commit_id, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/commits/%s', $commit_id);
        $result = $this->request('PATCH', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listRepoTags(string $repo_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/repositories/%s/tags', $repo_name);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function createRepoTag(string $repo_name, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/repositories/%s/tags', $repo_name);
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * Deploy a GitHub repository to a new Vers project.
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function deployHandler(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/deploy';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function execVm(string $vm_id, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/exec', $vm_id);
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function setRepositoryVisibility(string $repo_name, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/repositories/%s/visibility', $repo_name);
        $result = $this->request('PATCH', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function execVmStream(string $vm_id, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/exec/stream', $vm_id);
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param ListDomainsParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listDomains(?ListDomainsParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/domains';
        $query = [];
        if ($params !== null) {
            if ($params->vm_id !== null) {
                $query['vm_id'] = is_bool($params->vm_id) ? ($params->vm_id ? 'true' : 'false') : $params->vm_id;
            }
        }
        $result = $this->request('GET', $path, $options, null, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function createDomain(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/domains';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function sshKey(string $vm_id, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/ssh_key', $vm_id);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function listImages(?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/images';
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param ReadFileVmParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function readFileVm(string $vm_id, ?ReadFileVmParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/files', $vm_id);
        $query = [];
        if ($params !== null) {
            if ($params->path !== null) {
                $query['path'] = is_bool($params->path) ? ($params->path ? 'true' : 'false') : $params->path;
            }
        }
        $result = $this->request('GET', $path, $options, null, $query);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function writeFileVm(string $vm_id, ?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/%s/files', $vm_id);
        $result = $this->request('PUT', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param array<string, mixed>|null $body Request body
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function uploadImage(?array $body = null, ?RequestOptions $options = null): mixed
    {
        $path = '/api/v1/images/upload';
        $result = $this->request('POST', $path, $options, $body);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function getPublicRepository(string $org_name, string $repo_name, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/public/repositories/%s/%s', $org_name, $repo_name);
        $result = $this->request('GET', $path, $options);
        return $result['decoded'];
    }

    /**
     * 
     *
     * @param string $pathParams Path parameters
     * @param array<string, mixed>|null $body Request body
     * @param BranchByCommitParams|null $params Query parameters
     * @param RequestOptions|null $options Per-request options
     * @return mixed Decoded JSON response
     * @throws ApiException
     */
    public function branchByCommit(string $commit_id, ?array $body = null, ?BranchByCommitParams $params = null, ?RequestOptions $options = null): mixed
    {
        $path = sprintf('/api/v1/vm/branch/by_commit/%s', $commit_id);
        $query = [];
        if ($params !== null) {
            if ($params->count !== null) {
                $query['count'] = is_bool($params->count) ? ($params->count ? 'true' : 'false') : $params->count;
            }
        }
        $result = $this->request('POST', $path, $options, $body, $query);
        return $result['decoded'];
    }

}
