<?php

/**
 * Generated by Sterling SDK Generator
 * Orchestrator Control Plane API v0.1.0
 */

declare(strict_types=1);

namespace VersSdk;

class EnvVarsResponse
{
    /** All environment variables currently set for the authenticated user. */
    public readonly array $vars;

    public function __construct(
        array $vars,
    ) {
        $this->vars = $vars;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            vars: $data['vars'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->vars !== null) {
            $result['vars'] = $this->vars;
        }
        return $result;
    }
}

class CreateRepositoryResponse
{
    /** The name of the repository */
    public readonly string $name;
    /** The ID of the newly created repository */
    public readonly string $repo_id;

    public function __construct(
        string $name,
        string $repo_id,
    ) {
        $this->name = $name;
        $this->repo_id = $repo_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            name: $data['name'] ?? null,
            repo_id: $data['repo_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        if ($this->repo_id !== null) {
            $result['repo_id'] = $this->repo_id;
        }
        return $result;
    }
}

class PublicRepositoryInfo
{
    /** When the repository was created */
    public readonly string $created_at;
    /** Optional description */
    public readonly string|null $description;
    /** Full reference: org_name/repo_name */
    public readonly string $full_name;
    /** The repository name */
    public readonly string $name;
    /** The owning organization's name (namespace) */
    public readonly string $org_name;
    /** The repository's unique identifier */
    public readonly string $repo_id;

    public function __construct(
        string $created_at,
        string $full_name,
        string $name,
        string $org_name,
        string $repo_id,
        string|null $description = null,
    ) {
        $this->created_at = $created_at;
        $this->description = $description;
        $this->full_name = $full_name;
        $this->name = $name;
        $this->org_name = $org_name;
        $this->repo_id = $repo_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            created_at: $data['created_at'] ?? null,
            description: $data['description'] ?? null,
            full_name: $data['full_name'] ?? null,
            name: $data['name'] ?? null,
            org_name: $data['org_name'] ?? null,
            repo_id: $data['repo_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->full_name !== null) {
            $result['full_name'] = $this->full_name;
        }
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        if ($this->org_name !== null) {
            $result['org_name'] = $this->org_name;
        }
        if ($this->repo_id !== null) {
            $result['repo_id'] = $this->repo_id;
        }
        return $result;
    }
}

class ListTagsResponse
{
    /** List of all tags in the user's organization */
    public readonly array $tags;

    public function __construct(
        array $tags,
    ) {
        $this->tags = $tags;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            tags: $data['tags'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->tags !== null) {
            $result['tags'] = $this->tags;
        }
        return $result;
    }
}

class CreateRepoTagRequest
{
    /** The commit ID this tag should point to */
    public readonly string $commit_id;
    /** Optional description of what this tag represents */
    public readonly string|null $description;
    /** The tag name (e.g. 'latest', 'v1.0') */
    public readonly string $tag_name;

    public function __construct(
        string $commit_id,
        string $tag_name,
        string|null $description = null,
    ) {
        $this->commit_id = $commit_id;
        $this->description = $description;
        $this->tag_name = $tag_name;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            description: $data['description'] ?? null,
            tag_name: $data['tag_name'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->tag_name !== null) {
            $result['tag_name'] = $this->tag_name;
        }
        return $result;
    }
}

class OrchestratorVersion
{
    /** Executable identifier; should be 'orchestrator' */
    public readonly string $executable_name;
    /** Current git hash used for the build */
    public readonly string $git_hash;
    /** Current workspace version */
    public readonly string $workspace_version;

    public function __construct(
        string $executable_name,
        string $git_hash,
        string $workspace_version,
    ) {
        $this->executable_name = $executable_name;
        $this->git_hash = $git_hash;
        $this->workspace_version = $workspace_version;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            executable_name: $data['executable_name'] ?? null,
            git_hash: $data['git_hash'] ?? null,
            workspace_version: $data['workspace_version'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->executable_name !== null) {
            $result['executable_name'] = $this->executable_name;
        }
        if ($this->git_hash !== null) {
            $result['git_hash'] = $this->git_hash;
        }
        if ($this->workspace_version !== null) {
            $result['workspace_version'] = $this->workspace_version;
        }
        return $result;
    }
}

class ListCommitsResponse
{
    public readonly array $commits;
    public readonly int $limit;
    public readonly int $offset;
    public readonly int $total;

    public function __construct(
        array $commits,
        int $limit,
        int $offset,
        int $total,
    ) {
        $this->commits = $commits;
        $this->limit = $limit;
        $this->offset = $offset;
        $this->total = $total;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commits: $data['commits'] ?? null,
            limit: $data['limit'] ?? null,
            offset: $data['offset'] ?? null,
            total: $data['total'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commits !== null) {
            $result['commits'] = $this->commits;
        }
        if ($this->limit !== null) {
            $result['limit'] = $this->limit;
        }
        if ($this->offset !== null) {
            $result['offset'] = $this->offset;
        }
        if ($this->total !== null) {
            $result['total'] = $this->total;
        }
        return $result;
    }
}

class DeployResponse
{
    public readonly string $project_id;
    public readonly string $status;
    public readonly string $vm_id;

    public function __construct(
        string $project_id,
        string $status,
        string $vm_id,
    ) {
        $this->project_id = $project_id;
        $this->status = $status;
        $this->vm_id = $vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            project_id: $data['project_id'] ?? null,
            status: $data['status'] ?? null,
            vm_id: $data['vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->project_id !== null) {
            $result['project_id'] = $this->project_id;
        }
        if ($this->status !== null) {
            $result['status'] = $this->status;
        }
        if ($this->vm_id !== null) {
            $result['vm_id'] = $this->vm_id;
        }
        return $result;
    }
}

class ListRepoTagsResponse
{
    /** The repository name */
    public readonly string $repository;
    /** List of tags in this repository */
    public readonly array $tags;

    public function __construct(
        string $repository,
        array $tags,
    ) {
        $this->repository = $repository;
        $this->tags = $tags;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            repository: $data['repository'] ?? null,
            tags: $data['tags'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->repository !== null) {
            $result['repository'] = $this->repository;
        }
        if ($this->tags !== null) {
            $result['tags'] = $this->tags;
        }
        return $result;
    }
}

class BaseImageInfo
{
    public readonly string $base_image_id;
    public readonly string $created_at;
    public readonly string|null $description;
    public readonly string $image_name;
    public readonly bool $is_public;
    public readonly string $owner_id;
    public readonly int $size_mib;
    public readonly string $source_type;

    public function __construct(
        string $base_image_id,
        string $created_at,
        string $image_name,
        bool $is_public,
        string $owner_id,
        int $size_mib,
        string $source_type,
        string|null $description = null,
    ) {
        $this->base_image_id = $base_image_id;
        $this->created_at = $created_at;
        $this->description = $description;
        $this->image_name = $image_name;
        $this->is_public = $is_public;
        $this->owner_id = $owner_id;
        $this->size_mib = $size_mib;
        $this->source_type = $source_type;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            base_image_id: $data['base_image_id'] ?? null,
            created_at: $data['created_at'] ?? null,
            description: $data['description'] ?? null,
            image_name: $data['image_name'] ?? null,
            is_public: $data['is_public'] ?? null,
            owner_id: $data['owner_id'] ?? null,
            size_mib: $data['size_mib'] ?? null,
            source_type: $data['source_type'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->base_image_id !== null) {
            $result['base_image_id'] = $this->base_image_id;
        }
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->image_name !== null) {
            $result['image_name'] = $this->image_name;
        }
        if ($this->is_public !== null) {
            $result['is_public'] = $this->is_public;
        }
        if ($this->owner_id !== null) {
            $result['owner_id'] = $this->owner_id;
        }
        if ($this->size_mib !== null) {
            $result['size_mib'] = $this->size_mib;
        }
        if ($this->source_type !== null) {
            $result['source_type'] = $this->source_type;
        }
        return $result;
    }
}

class VmExecResponse
{
    /** Exec identifier associated with this run. */
    public readonly string|null $exec_id;
    /** Exit code returned by the command. */
    public readonly int $exit_code;
    /** UTF-8 decoded stderr (lossy). */
    public readonly string $stderr;
    /** UTF-8 decoded stdout (lossy). */
    public readonly string $stdout;

    public function __construct(
        int $exit_code,
        string $stderr,
        string $stdout,
        string|null $exec_id = null,
    ) {
        $this->exec_id = $exec_id;
        $this->exit_code = $exit_code;
        $this->stderr = $stderr;
        $this->stdout = $stdout;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            exec_id: $data['exec_id'] ?? null,
            exit_code: $data['exit_code'] ?? null,
            stderr: $data['stderr'] ?? null,
            stdout: $data['stdout'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->exec_id !== null) {
            $result['exec_id'] = $this->exec_id;
        }
        if ($this->exit_code !== null) {
            $result['exit_code'] = $this->exit_code;
        }
        if ($this->stderr !== null) {
            $result['stderr'] = $this->stderr;
        }
        if ($this->stdout !== null) {
            $result['stdout'] = $this->stdout;
        }
        return $result;
    }
}

class CreateBaseImageResponse
{
    public readonly string $image_name;
    public readonly string $job_id;
    public readonly string $status;

    public function __construct(
        string $image_name,
        string $job_id,
        string $status,
    ) {
        $this->image_name = $image_name;
        $this->job_id = $job_id;
        $this->status = $status;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            image_name: $data['image_name'] ?? null,
            job_id: $data['job_id'] ?? null,
            status: $data['status'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->image_name !== null) {
            $result['image_name'] = $this->image_name;
        }
        if ($this->job_id !== null) {
            $result['job_id'] = $this->job_id;
        }
        if ($this->status !== null) {
            $result['status'] = $this->status;
        }
        return $result;
    }
}

class VmExecRequest
{
    /** Command and arguments to execute. */
    public readonly array $command;
    /** Optional environment variables to set for the process. */
    public readonly array|null $env;
    /** Optional exec identifier for tracking. */
    public readonly string|null $exec_id;
    /** Optional stdin payload passed to the command. */
    public readonly string|null $stdin;
    /** Timeout in seconds (0 = no timeout). */
    public readonly int|null $timeout_secs;
    /** Optional working directory for the command. */
    public readonly string|null $working_dir;

    public function __construct(
        array $command,
        array|null $env = null,
        string|null $exec_id = null,
        string|null $stdin = null,
        int|null $timeout_secs = null,
        string|null $working_dir = null,
    ) {
        $this->command = $command;
        $this->env = $env;
        $this->exec_id = $exec_id;
        $this->stdin = $stdin;
        $this->timeout_secs = $timeout_secs;
        $this->working_dir = $working_dir;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            command: $data['command'] ?? null,
            env: $data['env'] ?? null,
            exec_id: $data['exec_id'] ?? null,
            stdin: $data['stdin'] ?? null,
            timeout_secs: $data['timeout_secs'] ?? null,
            working_dir: $data['working_dir'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->command !== null) {
            $result['command'] = $this->command;
        }
        if ($this->env !== null) {
            $result['env'] = $this->env;
        }
        if ($this->exec_id !== null) {
            $result['exec_id'] = $this->exec_id;
        }
        if ($this->stdin !== null) {
            $result['stdin'] = $this->stdin;
        }
        if ($this->timeout_secs !== null) {
            $result['timeout_secs'] = $this->timeout_secs;
        }
        if ($this->working_dir !== null) {
            $result['working_dir'] = $this->working_dir;
        }
        return $result;
    }
}

class NewVmsResponse
{
    public readonly array $vms;

    public function __construct(
        array $vms,
    ) {
        $this->vms = $vms;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            vms: $data['vms'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->vms !== null) {
            $result['vms'] = $this->vms;
        }
        return $result;
    }
}

class VmExecStreamAttachRequest
{
    /** Optional cursor to resume from (exclusive). If omitted, the full retained backlog is replayed. */
    public readonly int|null $cursor;
    /** Identifier of the exec stream session to reattach to. */
    public readonly string $exec_id;
    /** Start streaming after the latest retained chunk (ignores cursor). */
    public readonly bool|null $from_latest;

    public function __construct(
        string $exec_id,
        int|null $cursor = null,
        bool|null $from_latest = null,
    ) {
        $this->cursor = $cursor;
        $this->exec_id = $exec_id;
        $this->from_latest = $from_latest;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            cursor: $data['cursor'] ?? null,
            exec_id: $data['exec_id'] ?? null,
            from_latest: $data['from_latest'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->cursor !== null) {
            $result['cursor'] = $this->cursor;
        }
        if ($this->exec_id !== null) {
            $result['exec_id'] = $this->exec_id;
        }
        if ($this->from_latest !== null) {
            $result['from_latest'] = $this->from_latest;
        }
        return $result;
    }
}

class VmUpdateStateRequest
{
    /** The requested state for the VM */
    public readonly VmUpdateStateEnum $state;

    public function __construct(
        VmUpdateStateEnum $state,
    ) {
        $this->state = $state;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            state: isset($data['state']) ? VmUpdateStateEnum::fromArray($data['state']) : null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->state !== null) {
            $result['state'] = $this->state->toArray();
        }
        return $result;
    }
}

class DeleteBaseImageResponse
{
    public readonly string $base_image_id;
    public readonly bool $deleted;

    public function __construct(
        string $base_image_id,
        bool $deleted,
    ) {
        $this->base_image_id = $base_image_id;
        $this->deleted = $deleted;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            base_image_id: $data['base_image_id'] ?? null,
            deleted: $data['deleted'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->base_image_id !== null) {
            $result['base_image_id'] = $this->base_image_id;
        }
        if ($this->deleted !== null) {
            $result['deleted'] = $this->deleted;
        }
        return $result;
    }
}

class ListPublicRepositoriesResponse
{
    public readonly array $repositories;

    public function __construct(
        array $repositories,
    ) {
        $this->repositories = $repositories;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            repositories: $data['repositories'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->repositories !== null) {
            $result['repositories'] = $this->repositories;
        }
        return $result;
    }
}

class CreateTagRequest
{
    /** The commit ID this tag should point to */
    public readonly string $commit_id;
    /** Optional description of what this tag represents */
    public readonly string|null $description;
    /** The name of the tag (alphanumeric, hyphens, underscores, dots, 1-64 chars) */
    public readonly string $tag_name;

    public function __construct(
        string $commit_id,
        string $tag_name,
        string|null $description = null,
    ) {
        $this->commit_id = $commit_id;
        $this->description = $description;
        $this->tag_name = $tag_name;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            description: $data['description'] ?? null,
            tag_name: $data['tag_name'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->tag_name !== null) {
            $result['tag_name'] = $this->tag_name;
        }
        return $result;
    }
}

class ListRepositoriesResponse
{
    /** List of all repositories in the user's organization */
    public readonly array $repositories;

    public function __construct(
        array $repositories,
    ) {
        $this->repositories = $repositories;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            repositories: $data['repositories'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->repositories !== null) {
            $result['repositories'] = $this->repositories;
        }
        return $result;
    }
}

class CreateRepoTagResponse
{
    /** The commit ID this tag points to */
    public readonly string $commit_id;
    /** Full reference in image_name:tag format */
    public readonly string $reference;
    /** The ID of the newly created tag */
    public readonly string $tag_id;

    public function __construct(
        string $commit_id,
        string $reference,
        string $tag_id,
    ) {
        $this->commit_id = $commit_id;
        $this->reference = $reference;
        $this->tag_id = $tag_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            reference: $data['reference'] ?? null,
            tag_id: $data['tag_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->reference !== null) {
            $result['reference'] = $this->reference;
        }
        if ($this->tag_id !== null) {
            $result['tag_id'] = $this->tag_id;
        }
        return $result;
    }
}

class CommitInfo
{
    public readonly string $commit_id;
    public readonly string $created_at;
    public readonly string|null $description;
    public readonly string|null $grandparent_commit_id;
    public readonly bool $is_public;
    public readonly string $name;
    public readonly string $owner_id;
    public readonly string|null $parent_vm_id;

    public function __construct(
        string $commit_id,
        string $created_at,
        bool $is_public,
        string $name,
        string $owner_id,
        string|null $description = null,
        string|null $grandparent_commit_id = null,
        string|null $parent_vm_id = null,
    ) {
        $this->commit_id = $commit_id;
        $this->created_at = $created_at;
        $this->description = $description;
        $this->grandparent_commit_id = $grandparent_commit_id;
        $this->is_public = $is_public;
        $this->name = $name;
        $this->owner_id = $owner_id;
        $this->parent_vm_id = $parent_vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            created_at: $data['created_at'] ?? null,
            description: $data['description'] ?? null,
            grandparent_commit_id: $data['grandparent_commit_id'] ?? null,
            is_public: $data['is_public'] ?? null,
            name: $data['name'] ?? null,
            owner_id: $data['owner_id'] ?? null,
            parent_vm_id: $data['parent_vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->grandparent_commit_id !== null) {
            $result['grandparent_commit_id'] = $this->grandparent_commit_id;
        }
        if ($this->is_public !== null) {
            $result['is_public'] = $this->is_public;
        }
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        if ($this->owner_id !== null) {
            $result['owner_id'] = $this->owner_id;
        }
        if ($this->parent_vm_id !== null) {
            $result['parent_vm_id'] = $this->parent_vm_id;
        }
        return $result;
    }
}

class DeleteDomainResponse
{
    public readonly string $domain_id;

    public function __construct(
        string $domain_id,
    ) {
        $this->domain_id = $domain_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            domain_id: $data['domain_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->domain_id !== null) {
            $result['domain_id'] = $this->domain_id;
        }
        return $result;
    }
}

class RepositoryInfo
{
    /** When the repository was created */
    public readonly string $created_at;
    /** Optional description */
    public readonly string|null $description;
    /** Whether this repository is publicly visible */
    public readonly bool $is_public;
    /** The repository name */
    public readonly string $name;
    /** The repository's unique identifier */
    public readonly string $repo_id;

    public function __construct(
        string $created_at,
        bool $is_public,
        string $name,
        string $repo_id,
        string|null $description = null,
    ) {
        $this->created_at = $created_at;
        $this->description = $description;
        $this->is_public = $is_public;
        $this->name = $name;
        $this->repo_id = $repo_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            created_at: $data['created_at'] ?? null,
            description: $data['description'] ?? null,
            is_public: $data['is_public'] ?? null,
            name: $data['name'] ?? null,
            repo_id: $data['repo_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->is_public !== null) {
            $result['is_public'] = $this->is_public;
        }
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        if ($this->repo_id !== null) {
            $result['repo_id'] = $this->repo_id;
        }
        return $result;
    }
}

class ValidateKeyResponse
{
    public readonly string $message;
    public readonly bool $valid;

    public function __construct(
        string $message,
        bool $valid,
    ) {
        $this->message = $message;
        $this->valid = $valid;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            message: $data['message'] ?? null,
            valid: $data['valid'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->message !== null) {
            $result['message'] = $this->message;
        }
        if ($this->valid !== null) {
            $result['valid'] = $this->valid;
        }
        return $result;
    }
}

class VmSshKeyResponse
{
    /** The SSH port that will be DNAT'd to the VM's netns (and, in turn, to its TAP device) */
    public readonly int $ssh_port;
    /** Private SSH key in stringified OpenSSH format */
    public readonly string $ssh_private_key;

    public function __construct(
        int $ssh_port,
        string $ssh_private_key,
    ) {
        $this->ssh_port = $ssh_port;
        $this->ssh_private_key = $ssh_private_key;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            ssh_port: $data['ssh_port'] ?? null,
            ssh_private_key: $data['ssh_private_key'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->ssh_port !== null) {
            $result['ssh_port'] = $this->ssh_port;
        }
        if ($this->ssh_private_key !== null) {
            $result['ssh_private_key'] = $this->ssh_private_key;
        }
        return $result;
    }
}

enum VmState: string
{
    case Booting = 'booting';
    case Running = 'running';
    case Paused = 'paused';
    case Sleeping = 'sleeping';
    case Dead = 'dead';
}

class VmReadFileResponse
{
    /** File contents, base64-encoded. */
    public readonly string $content_b64;

    public function __construct(
        string $content_b64,
    ) {
        $this->content_b64 = $content_b64;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            content_b64: $data['content_b64'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->content_b64 !== null) {
            $result['content_b64'] = $this->content_b64;
        }
        return $result;
    }
}

class SetEnvVarsRequest
{
    /** If true, delete all existing variables before writing the new set. This gives 'set exactly these vars' semantics. Default: false (upsert). */
    public readonly bool|null $replace;
    /** Key-value pairs to set. Keys must be valid shell identifiers (`^[A-Za-z_][A-Za-z0-9_]*$`, max 256 chars). Values max 8192 chars.  When `replace` is false (default): existing keys are overwritten, keys not mentioned are left untouched (upsert semantics).  When `replace` is true: all existing variables are deleted first, then only the provided vars are stored (replace-all semantics). */
    public readonly array $vars;

    public function __construct(
        array $vars,
        bool|null $replace = null,
    ) {
        $this->replace = $replace;
        $this->vars = $vars;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            replace: $data['replace'] ?? null,
            vars: $data['vars'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->replace !== null) {
            $result['replace'] = $this->replace;
        }
        if ($this->vars !== null) {
            $result['vars'] = $this->vars;
        }
        return $result;
    }
}

class VmCommitResponse
{
    /** The UUID of the newly-created commit */
    public readonly string $commit_id;

    public function __construct(
        string $commit_id,
    ) {
        $this->commit_id = $commit_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        return $result;
    }
}

class ForkRepositoryResponse
{
    /** The new commit in your org (snapshot of the forked VM) */
    public readonly string $commit_id;
    /** Full reference: repo_name:tag_name */
    public readonly string $reference;
    /** The new repository name in your org */
    public readonly string $repo_name;
    /** The tag name pointing to the forked commit */
    public readonly string $tag_name;
    /** The new VM that was created from the fork */
    public readonly string $vm_id;

    public function __construct(
        string $commit_id,
        string $reference,
        string $repo_name,
        string $tag_name,
        string $vm_id,
    ) {
        $this->commit_id = $commit_id;
        $this->reference = $reference;
        $this->repo_name = $repo_name;
        $this->tag_name = $tag_name;
        $this->vm_id = $vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            reference: $data['reference'] ?? null,
            repo_name: $data['repo_name'] ?? null,
            tag_name: $data['tag_name'] ?? null,
            vm_id: $data['vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->reference !== null) {
            $result['reference'] = $this->reference;
        }
        if ($this->repo_name !== null) {
            $result['repo_name'] = $this->repo_name;
        }
        if ($this->tag_name !== null) {
            $result['tag_name'] = $this->tag_name;
        }
        if ($this->vm_id !== null) {
            $result['vm_id'] = $this->vm_id;
        }
        return $result;
    }
}

// Union type: ImageSourceRequest
// Use one of the following variant classes:
class ImageSourceRequestImageRefVariant
{
    public readonly string $image_ref;
    public readonly string $type;

    public function __construct(
        string $image_ref,
        string $type
    ) {
        $this->image_ref = $image_ref;
        $this->type = $type;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            image_ref: $data['image_ref'] ?? null,
            type: $data['type'] ?? null
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'image_ref' => $this->image_ref,
            'type' => $this->type
        ];
    }
}

class ImageSourceRequestBucketVariant
{
    public readonly string $bucket;
    public readonly string $key;
    public readonly string $type;

    public function __construct(
        string $bucket,
        string $key,
        string $type
    ) {
        $this->bucket = $bucket;
        $this->key = $key;
        $this->type = $type;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            bucket: $data['bucket'] ?? null,
            key: $data['key'] ?? null,
            type: $data['type'] ?? null
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'bucket' => $this->bucket,
            'key' => $this->key,
            'type' => $this->type
        ];
    }
}

enum VmUpdateStateEnum: string
{
    case Paused = 'Paused';
    case Running = 'Running';
}

class ErrorResponse
{
    /** Reason of error */
    public readonly string|null $error;
    /** Is always: false */
    public readonly bool|null $success;

    public function __construct(
        string|null $error = null,
        bool|null $success = null,
    ) {
        $this->error = $error;
        $this->success = $success;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            error: $data['error'] ?? null,
            success: $data['success'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->error !== null) {
            $result['error'] = $this->error;
        }
        if ($this->success !== null) {
            $result['success'] = $this->success;
        }
        return $result;
    }
}

class UpdateCommitRequest
{
    /** Optional description for the commit. */
    public readonly string|null $description;
    public readonly bool $is_public;
    /** Optional human-readable name for the commit. */
    public readonly string|null $name;

    public function __construct(
        bool $is_public,
        string|null $description = null,
        string|null $name = null,
    ) {
        $this->description = $description;
        $this->is_public = $is_public;
        $this->name = $name;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            description: $data['description'] ?? null,
            is_public: $data['is_public'] ?? null,
            name: $data['name'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->is_public !== null) {
            $result['is_public'] = $this->is_public;
        }
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        return $result;
    }
}

class CreateRepositoryRequest
{
    /** Optional description of the repository */
    public readonly string|null $description;
    /** The name of the repository (alphanumeric, hyphens, underscores, dots, 1-64 chars) */
    public readonly string $name;

    public function __construct(
        string $name,
        string|null $description = null,
    ) {
        $this->description = $description;
        $this->name = $name;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            description: $data['description'] ?? null,
            name: $data['name'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        return $result;
    }
}

class DomainResponse
{
    public readonly string $created_at;
    public readonly string $domain;
    public readonly string $domain_id;
    public readonly string $vm_id;

    public function __construct(
        string $created_at,
        string $domain,
        string $domain_id,
        string $vm_id,
    ) {
        $this->created_at = $created_at;
        $this->domain = $domain;
        $this->domain_id = $domain_id;
        $this->vm_id = $vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            created_at: $data['created_at'] ?? null,
            domain: $data['domain'] ?? null,
            domain_id: $data['domain_id'] ?? null,
            vm_id: $data['vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->domain !== null) {
            $result['domain'] = $this->domain;
        }
        if ($this->domain_id !== null) {
            $result['domain_id'] = $this->domain_id;
        }
        if ($this->vm_id !== null) {
            $result['vm_id'] = $this->vm_id;
        }
        return $result;
    }
}

class VmCommitRequest
{
    /** If provided, chelsea will use the requested commit UUID. Otherwise, it will generate a UUID itself. */
    public readonly string|null $commit_id;
    /** Optional description for the commit. */
    public readonly string|null $description;
    /** Optional human-readable name for the commit. Defaults to auto-generated name if not provided. */
    public readonly string|null $name;

    public function __construct(
        string|null $commit_id = null,
        string|null $description = null,
        string|null $name = null,
    ) {
        $this->commit_id = $commit_id;
        $this->description = $description;
        $this->name = $name;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            description: $data['description'] ?? null,
            name: $data['name'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        return $result;
    }
}

class DeploySettings
{
    public readonly string|null $build_command;
    public readonly string|null $install_command;
    public readonly string|null $run_command;
    public readonly string|null $working_directory;

    public function __construct(
        string|null $build_command = null,
        string|null $install_command = null,
        string|null $run_command = null,
        string|null $working_directory = null,
    ) {
        $this->build_command = $build_command;
        $this->install_command = $install_command;
        $this->run_command = $run_command;
        $this->working_directory = $working_directory;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            build_command: $data['build_command'] ?? null,
            install_command: $data['install_command'] ?? null,
            run_command: $data['run_command'] ?? null,
            working_directory: $data['working_directory'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->build_command !== null) {
            $result['build_command'] = $this->build_command;
        }
        if ($this->install_command !== null) {
            $result['install_command'] = $this->install_command;
        }
        if ($this->run_command !== null) {
            $result['run_command'] = $this->run_command;
        }
        if ($this->working_directory !== null) {
            $result['working_directory'] = $this->working_directory;
        }
        return $result;
    }
}

class CreateBaseImageRequest
{
    public readonly string|null $description;
    public readonly string $image_name;
    /** Additional capacity in MiB beyond the actual filesystem size (defaults to 256). The final image size = calculated rootfs size + this value. Set to 0 for minimum possible image size, or higher for more free space. */
    public readonly int|null $size_mib;
    public readonly ImageSourceRequest $source;

    public function __construct(
        string $image_name,
        ImageSourceRequest $source,
        string|null $description = null,
        int|null $size_mib = null,
    ) {
        $this->description = $description;
        $this->image_name = $image_name;
        $this->size_mib = $size_mib;
        $this->source = $source;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            description: $data['description'] ?? null,
            image_name: $data['image_name'] ?? null,
            size_mib: $data['size_mib'] ?? null,
            source: isset($data['source']) ? ImageSourceRequest::fromArray($data['source']) : null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->image_name !== null) {
            $result['image_name'] = $this->image_name;
        }
        if ($this->size_mib !== null) {
            $result['size_mib'] = $this->size_mib;
        }
        if ($this->source !== null) {
            $result['source'] = $this->source->toArray();
        }
        return $result;
    }
}

class ForkRepositoryRequest
{
    /** Name for the new repository in your org (defaults to source_repo if omitted) */
    public readonly string|null $repo_name;
    /** The organization that owns the source public repository */
    public readonly string $source_org;
    /** The source repository name */
    public readonly string $source_repo;
    /** The tag to fork (e.g. 'latest', 'v1.0') */
    public readonly string $source_tag;
    /** Tag name in the new repo (defaults to source_tag if omitted) */
    public readonly string|null $tag_name;

    public function __construct(
        string $source_org,
        string $source_repo,
        string $source_tag,
        string|null $repo_name = null,
        string|null $tag_name = null,
    ) {
        $this->repo_name = $repo_name;
        $this->source_org = $source_org;
        $this->source_repo = $source_repo;
        $this->source_tag = $source_tag;
        $this->tag_name = $tag_name;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            repo_name: $data['repo_name'] ?? null,
            source_org: $data['source_org'] ?? null,
            source_repo: $data['source_repo'] ?? null,
            source_tag: $data['source_tag'] ?? null,
            tag_name: $data['tag_name'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->repo_name !== null) {
            $result['repo_name'] = $this->repo_name;
        }
        if ($this->source_org !== null) {
            $result['source_org'] = $this->source_org;
        }
        if ($this->source_repo !== null) {
            $result['source_repo'] = $this->source_repo;
        }
        if ($this->source_tag !== null) {
            $result['source_tag'] = $this->source_tag;
        }
        if ($this->tag_name !== null) {
            $result['tag_name'] = $this->tag_name;
        }
        return $result;
    }
}

class VmCommitEntity
{
    public readonly string $created_at;
    public readonly string|null $description;
    /** The commit that this commit's parent VM was started from, if any. Intended to optimize traversing the commit tree. */
    public readonly string|null $grandparent_commit_id;
    public readonly string $id;
    /** Whether this commit is publicly accessible (readable/restorable by anyone). */
    public readonly bool $is_public;
    public readonly string $name;
    /** api key id. */
    public readonly string $owner_id;
    /** The VM that this commit was created from, if any. */
    public readonly string|null $parent_vm_id;

    public function __construct(
        string $created_at,
        string $id,
        bool $is_public,
        string $name,
        string $owner_id,
        string|null $description = null,
        string|null $grandparent_commit_id = null,
        string|null $parent_vm_id = null,
    ) {
        $this->created_at = $created_at;
        $this->description = $description;
        $this->grandparent_commit_id = $grandparent_commit_id;
        $this->id = $id;
        $this->is_public = $is_public;
        $this->name = $name;
        $this->owner_id = $owner_id;
        $this->parent_vm_id = $parent_vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            created_at: $data['created_at'] ?? null,
            description: $data['description'] ?? null,
            grandparent_commit_id: $data['grandparent_commit_id'] ?? null,
            id: $data['id'] ?? null,
            is_public: $data['is_public'] ?? null,
            name: $data['name'] ?? null,
            owner_id: $data['owner_id'] ?? null,
            parent_vm_id: $data['parent_vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->grandparent_commit_id !== null) {
            $result['grandparent_commit_id'] = $this->grandparent_commit_id;
        }
        if ($this->id !== null) {
            $result['id'] = $this->id;
        }
        if ($this->is_public !== null) {
            $result['is_public'] = $this->is_public;
        }
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        if ($this->owner_id !== null) {
            $result['owner_id'] = $this->owner_id;
        }
        if ($this->parent_vm_id !== null) {
            $result['parent_vm_id'] = $this->parent_vm_id;
        }
        return $result;
    }
}

class TagInfo
{
    /** The commit ID this tag currently points to */
    public readonly string $commit_id;
    /** When the tag was created */
    public readonly string $created_at;
    /** Optional description of what this tag represents */
    public readonly string|null $description;
    /** The tag's unique identifier */
    public readonly string $tag_id;
    /** The name of the tag */
    public readonly string $tag_name;
    /** When the tag was last updated (moved to different commit or description changed) */
    public readonly string $updated_at;

    public function __construct(
        string $commit_id,
        string $created_at,
        string $tag_id,
        string $tag_name,
        string $updated_at,
        string|null $description = null,
    ) {
        $this->commit_id = $commit_id;
        $this->created_at = $created_at;
        $this->description = $description;
        $this->tag_id = $tag_id;
        $this->tag_name = $tag_name;
        $this->updated_at = $updated_at;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            created_at: $data['created_at'] ?? null,
            description: $data['description'] ?? null,
            tag_id: $data['tag_id'] ?? null,
            tag_name: $data['tag_name'] ?? null,
            updated_at: $data['updated_at'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->tag_id !== null) {
            $result['tag_id'] = $this->tag_id;
        }
        if ($this->tag_name !== null) {
            $result['tag_name'] = $this->tag_name;
        }
        if ($this->updated_at !== null) {
            $result['updated_at'] = $this->updated_at;
        }
        return $result;
    }
}

class VmWriteFileRequest
{
    /** File contents, base64-encoded. */
    public readonly string $content_b64;
    /** Create parent directories if they don't exist. */
    public readonly bool|null $create_dirs;
    /** File mode (e.g. 0644). Defaults to 0644 if omitted. */
    public readonly int|null $mode;
    /** Destination path on the VM. */
    public readonly string $path;

    public function __construct(
        string $content_b64,
        string $path,
        bool|null $create_dirs = null,
        int|null $mode = null,
    ) {
        $this->content_b64 = $content_b64;
        $this->create_dirs = $create_dirs;
        $this->mode = $mode;
        $this->path = $path;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            content_b64: $data['content_b64'] ?? null,
            create_dirs: $data['create_dirs'] ?? null,
            mode: $data['mode'] ?? null,
            path: $data['path'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->content_b64 !== null) {
            $result['content_b64'] = $this->content_b64;
        }
        if ($this->create_dirs !== null) {
            $result['create_dirs'] = $this->create_dirs;
        }
        if ($this->mode !== null) {
            $result['mode'] = $this->mode;
        }
        if ($this->path !== null) {
            $result['path'] = $this->path;
        }
        return $result;
    }
}

enum VmExecLogStream: string
{
    case Stdout = 'stdout';
    case Stderr = 'stderr';
}

class VmExecLogEntry
{
    /** Base64-encoded bytes from stdout/stderr chunk. */
    public readonly string $data_b64;
    public readonly string|null $exec_id;
    public readonly VmExecLogStream $stream;
    public readonly string $timestamp;

    public function __construct(
        string $data_b64,
        VmExecLogStream $stream,
        string $timestamp,
        string|null $exec_id = null,
    ) {
        $this->data_b64 = $data_b64;
        $this->exec_id = $exec_id;
        $this->stream = $stream;
        $this->timestamp = $timestamp;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            data_b64: $data['data_b64'] ?? null,
            exec_id: $data['exec_id'] ?? null,
            stream: isset($data['stream']) ? VmExecLogStream::fromArray($data['stream']) : null,
            timestamp: $data['timestamp'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->data_b64 !== null) {
            $result['data_b64'] = $this->data_b64;
        }
        if ($this->exec_id !== null) {
            $result['exec_id'] = $this->exec_id;
        }
        if ($this->stream !== null) {
            $result['stream'] = $this->stream->toArray();
        }
        if ($this->timestamp !== null) {
            $result['timestamp'] = $this->timestamp;
        }
        return $result;
    }
}

class LabelVmRequest
{
    public readonly array|null $labels;

    public function __construct(
        array|null $labels = null,
    ) {
        $this->labels = $labels;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            labels: $data['labels'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->labels !== null) {
            $result['labels'] = $this->labels;
        }
        return $result;
    }
}

class VmMetadataResponse
{
    public readonly string $created_at;
    public readonly string|null $deleted_at;
    public readonly string|null $grandparent_vm_id;
    public readonly string $ip;
    public readonly string $owner_id;
    public readonly string|null $parent_commit_id;
    public readonly VmState $state;
    public readonly string $vm_id;

    public function __construct(
        string $created_at,
        string $ip,
        string $owner_id,
        VmState $state,
        string $vm_id,
        string|null $deleted_at = null,
        string|null $grandparent_vm_id = null,
        string|null $parent_commit_id = null,
    ) {
        $this->created_at = $created_at;
        $this->deleted_at = $deleted_at;
        $this->grandparent_vm_id = $grandparent_vm_id;
        $this->ip = $ip;
        $this->owner_id = $owner_id;
        $this->parent_commit_id = $parent_commit_id;
        $this->state = $state;
        $this->vm_id = $vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            created_at: $data['created_at'] ?? null,
            deleted_at: $data['deleted_at'] ?? null,
            grandparent_vm_id: $data['grandparent_vm_id'] ?? null,
            ip: $data['ip'] ?? null,
            owner_id: $data['owner_id'] ?? null,
            parent_commit_id: $data['parent_commit_id'] ?? null,
            state: isset($data['state']) ? VmState::fromArray($data['state']) : null,
            vm_id: $data['vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->deleted_at !== null) {
            $result['deleted_at'] = $this->deleted_at;
        }
        if ($this->grandparent_vm_id !== null) {
            $result['grandparent_vm_id'] = $this->grandparent_vm_id;
        }
        if ($this->ip !== null) {
            $result['ip'] = $this->ip;
        }
        if ($this->owner_id !== null) {
            $result['owner_id'] = $this->owner_id;
        }
        if ($this->parent_commit_id !== null) {
            $result['parent_commit_id'] = $this->parent_commit_id;
        }
        if ($this->state !== null) {
            $result['state'] = $this->state->toArray();
        }
        if ($this->vm_id !== null) {
            $result['vm_id'] = $this->vm_id;
        }
        return $result;
    }
}

class SetRepositoryVisibilityRequest
{
    /** Whether the repository should be publicly visible */
    public readonly bool $is_public;

    public function __construct(
        bool $is_public,
    ) {
        $this->is_public = $is_public;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            is_public: $data['is_public'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->is_public !== null) {
            $result['is_public'] = $this->is_public;
        }
        return $result;
    }
}

class UpdateRepoTagRequest
{
    /** Optional new commit ID to move the tag to */
    public readonly string|null $commit_id;
    /** Optional new description for the tag. Send `null` to clear. */
    public readonly string|null $description;

    public function __construct(
        string|null $commit_id = null,
        string|null $description = null,
    ) {
        $this->commit_id = $commit_id;
        $this->description = $description;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            description: $data['description'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        return $result;
    }
}

class VmCreateVmConfig
{
    /** The disk size, in MiB. */
    public readonly int|null $fs_size_mib;
    /** The filesystem base image name. Currently, must be 'default' */
    public readonly string|null $image_name;
    /** The kernel name. Currently, must be 'default.bin' */
    public readonly string|null $kernel_name;
    public readonly array|null $labels;
    /** The RAM size, in MiB. */
    public readonly int|null $mem_size_mib;
    /** How many vCPUs to allocate to this VM (and its children) */
    public readonly int|null $vcpu_count;

    public function __construct(
        int|null $fs_size_mib = null,
        string|null $image_name = null,
        string|null $kernel_name = null,
        array|null $labels = null,
        int|null $mem_size_mib = null,
        int|null $vcpu_count = null,
    ) {
        $this->fs_size_mib = $fs_size_mib;
        $this->image_name = $image_name;
        $this->kernel_name = $kernel_name;
        $this->labels = $labels;
        $this->mem_size_mib = $mem_size_mib;
        $this->vcpu_count = $vcpu_count;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            fs_size_mib: $data['fs_size_mib'] ?? null,
            image_name: $data['image_name'] ?? null,
            kernel_name: $data['kernel_name'] ?? null,
            labels: $data['labels'] ?? null,
            mem_size_mib: $data['mem_size_mib'] ?? null,
            vcpu_count: $data['vcpu_count'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->fs_size_mib !== null) {
            $result['fs_size_mib'] = $this->fs_size_mib;
        }
        if ($this->image_name !== null) {
            $result['image_name'] = $this->image_name;
        }
        if ($this->kernel_name !== null) {
            $result['kernel_name'] = $this->kernel_name;
        }
        if ($this->labels !== null) {
            $result['labels'] = $this->labels;
        }
        if ($this->mem_size_mib !== null) {
            $result['mem_size_mib'] = $this->mem_size_mib;
        }
        if ($this->vcpu_count !== null) {
            $result['vcpu_count'] = $this->vcpu_count;
        }
        return $result;
    }
}

class NewVmResponse
{
    public readonly string $vm_id;

    public function __construct(
        string $vm_id,
    ) {
        $this->vm_id = $vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            vm_id: $data['vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->vm_id !== null) {
            $result['vm_id'] = $this->vm_id;
        }
        return $result;
    }
}

// Union type: FromCommitVmRequest
// Use one of the following variant classes:
class FromCommitVmRequestCommitIdVariant
{
    public readonly string $commit_id;

    public function __construct(
        string $commit_id
    ) {
        $this->commit_id = $commit_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'commit_id' => $this->commit_id
        ];
    }
}

class FromCommitVmRequestTagNameVariant
{
    public readonly string $tag_name;

    public function __construct(
        string $tag_name
    ) {
        $this->tag_name = $tag_name;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            tag_name: $data['tag_name'] ?? null
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'tag_name' => $this->tag_name
        ];
    }
}

class FromCommitVmRequestRefVariant
{
    public readonly string $ref;

    public function __construct(
        string $ref
    ) {
        $this->ref = $ref;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            ref: $data['ref'] ?? null
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'ref' => $this->ref
        ];
    }
}

class VM
{
    public readonly string $created_at;
    public readonly array|null $labels;
    public readonly string $owner_id;
    public readonly VmState $state;
    public readonly string $vm_id;

    public function __construct(
        string $created_at,
        string $owner_id,
        VmState $state,
        string $vm_id,
        array|null $labels = null,
    ) {
        $this->created_at = $created_at;
        $this->labels = $labels;
        $this->owner_id = $owner_id;
        $this->state = $state;
        $this->vm_id = $vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            created_at: $data['created_at'] ?? null,
            labels: $data['labels'] ?? null,
            owner_id: $data['owner_id'] ?? null,
            state: isset($data['state']) ? VmState::fromArray($data['state']) : null,
            vm_id: $data['vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->labels !== null) {
            $result['labels'] = $this->labels;
        }
        if ($this->owner_id !== null) {
            $result['owner_id'] = $this->owner_id;
        }
        if ($this->state !== null) {
            $result['state'] = $this->state->toArray();
        }
        if ($this->vm_id !== null) {
            $result['vm_id'] = $this->vm_id;
        }
        return $result;
    }
}

class CreateDomainRequest
{
    public readonly string $domain;
    public readonly string $vm_id;

    public function __construct(
        string $domain,
        string $vm_id,
    ) {
        $this->domain = $domain;
        $this->vm_id = $vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            domain: $data['domain'] ?? null,
            vm_id: $data['vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->domain !== null) {
            $result['domain'] = $this->domain;
        }
        if ($this->vm_id !== null) {
            $result['vm_id'] = $this->vm_id;
        }
        return $result;
    }
}

class UpdateTagRequest
{
    /** Optional new commit ID to move the tag to */
    public readonly string|null $commit_id;
    /** Optional new description for the tag. Send `null` to clear an existing description. */
    public readonly string|null $description;

    public function __construct(
        string|null $commit_id = null,
        string|null $description = null,
    ) {
        $this->commit_id = $commit_id;
        $this->description = $description;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            description: $data['description'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        return $result;
    }
}

class UploadBaseImageResponse
{
    public readonly string $image_name;
    public readonly string $job_id;
    public readonly string $status;

    public function __construct(
        string $image_name,
        string $job_id,
        string $status,
    ) {
        $this->image_name = $image_name;
        $this->job_id = $job_id;
        $this->status = $status;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            image_name: $data['image_name'] ?? null,
            job_id: $data['job_id'] ?? null,
            status: $data['status'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->image_name !== null) {
            $result['image_name'] = $this->image_name;
        }
        if ($this->job_id !== null) {
            $result['job_id'] = $this->job_id;
        }
        if ($this->status !== null) {
            $result['status'] = $this->status;
        }
        return $result;
    }
}

class BaseImageStatusResponse
{
    public readonly string|null $error_message;
    public readonly string $image_name;
    public readonly int $size_mib;
    public readonly string $status;

    public function __construct(
        string $image_name,
        int $size_mib,
        string $status,
        string|null $error_message = null,
    ) {
        $this->error_message = $error_message;
        $this->image_name = $image_name;
        $this->size_mib = $size_mib;
        $this->status = $status;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            error_message: $data['error_message'] ?? null,
            image_name: $data['image_name'] ?? null,
            size_mib: $data['size_mib'] ?? null,
            status: $data['status'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->error_message !== null) {
            $result['error_message'] = $this->error_message;
        }
        if ($this->image_name !== null) {
            $result['image_name'] = $this->image_name;
        }
        if ($this->size_mib !== null) {
            $result['size_mib'] = $this->size_mib;
        }
        if ($this->status !== null) {
            $result['status'] = $this->status;
        }
        return $result;
    }
}

class ListBaseImagesResponse
{
    public readonly array $images;
    public readonly int $limit;
    public readonly int $offset;
    public readonly int $total;

    public function __construct(
        array $images,
        int $limit,
        int $offset,
        int $total,
    ) {
        $this->images = $images;
        $this->limit = $limit;
        $this->offset = $offset;
        $this->total = $total;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            images: $data['images'] ?? null,
            limit: $data['limit'] ?? null,
            offset: $data['offset'] ?? null,
            total: $data['total'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->images !== null) {
            $result['images'] = $this->images;
        }
        if ($this->limit !== null) {
            $result['limit'] = $this->limit;
        }
        if ($this->offset !== null) {
            $result['offset'] = $this->offset;
        }
        if ($this->total !== null) {
            $result['total'] = $this->total;
        }
        return $result;
    }
}

class NewRootRequest
{
    public readonly VmCreateVmConfig $vm_config;

    public function __construct(
        VmCreateVmConfig $vm_config,
    ) {
        $this->vm_config = $vm_config;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            vm_config: isset($data['vm_config']) ? VmCreateVmConfig::fromArray($data['vm_config']) : null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->vm_config !== null) {
            $result['vm_config'] = $this->vm_config->toArray();
        }
        return $result;
    }
}

class VmResizeDiskRequest
{
    /** The new disk size in MiB. Must be strictly greater than the current size. */
    public readonly int $fs_size_mib;

    public function __construct(
        int $fs_size_mib,
    ) {
        $this->fs_size_mib = $fs_size_mib;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            fs_size_mib: $data['fs_size_mib'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->fs_size_mib !== null) {
            $result['fs_size_mib'] = $this->fs_size_mib;
        }
        return $result;
    }
}

class VmDeleteResponse
{
    public readonly string $vm_id;

    public function __construct(
        string $vm_id,
    ) {
        $this->vm_id = $vm_id;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            vm_id: $data['vm_id'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->vm_id !== null) {
            $result['vm_id'] = $this->vm_id;
        }
        return $result;
    }
}

class CreateTagResponse
{
    /** The commit ID this tag points to */
    public readonly string $commit_id;
    /** The ID of the newly created tag */
    public readonly string $tag_id;
    /** The name of the tag */
    public readonly string $tag_name;

    public function __construct(
        string $commit_id,
        string $tag_id,
        string $tag_name,
    ) {
        $this->commit_id = $commit_id;
        $this->tag_id = $tag_id;
        $this->tag_name = $tag_name;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            tag_id: $data['tag_id'] ?? null,
            tag_name: $data['tag_name'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->tag_id !== null) {
            $result['tag_id'] = $this->tag_id;
        }
        if ($this->tag_name !== null) {
            $result['tag_name'] = $this->tag_name;
        }
        return $result;
    }
}

class DeployRequest
{
    /** Git branch to clone (defaults to repo default branch). */
    public readonly string|null $branch;
    /** Optional project name (defaults to repo name). */
    public readonly string|null $name;
    /** GitHub repository in `owner/repo` format. */
    public readonly string $repo;
    public readonly object|null $settings;

    public function __construct(
        string $repo,
        string|null $branch = null,
        string|null $name = null,
        object|null $settings = null,
    ) {
        $this->branch = $branch;
        $this->name = $name;
        $this->repo = $repo;
        $this->settings = $settings;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            branch: $data['branch'] ?? null,
            name: $data['name'] ?? null,
            repo: $data['repo'] ?? null,
            settings: $data['settings'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->branch !== null) {
            $result['branch'] = $this->branch;
        }
        if ($this->name !== null) {
            $result['name'] = $this->name;
        }
        if ($this->repo !== null) {
            $result['repo'] = $this->repo;
        }
        if ($this->settings !== null) {
            $result['settings'] = $this->settings;
        }
        return $result;
    }
}

class RepoTagInfo
{
    /** The commit ID this tag currently points to */
    public readonly string $commit_id;
    /** When the tag was created */
    public readonly string $created_at;
    /** Optional description */
    public readonly string|null $description;
    /** Full reference in image_name:tag format */
    public readonly string $reference;
    /** The tag's unique identifier */
    public readonly string $tag_id;
    /** The tag name */
    public readonly string $tag_name;
    /** When the tag was last updated */
    public readonly string $updated_at;

    public function __construct(
        string $commit_id,
        string $created_at,
        string $reference,
        string $tag_id,
        string $tag_name,
        string $updated_at,
        string|null $description = null,
    ) {
        $this->commit_id = $commit_id;
        $this->created_at = $created_at;
        $this->description = $description;
        $this->reference = $reference;
        $this->tag_id = $tag_id;
        $this->tag_name = $tag_name;
        $this->updated_at = $updated_at;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            commit_id: $data['commit_id'] ?? null,
            created_at: $data['created_at'] ?? null,
            description: $data['description'] ?? null,
            reference: $data['reference'] ?? null,
            tag_id: $data['tag_id'] ?? null,
            tag_name: $data['tag_name'] ?? null,
            updated_at: $data['updated_at'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->commit_id !== null) {
            $result['commit_id'] = $this->commit_id;
        }
        if ($this->created_at !== null) {
            $result['created_at'] = $this->created_at;
        }
        if ($this->description !== null) {
            $result['description'] = $this->description;
        }
        if ($this->reference !== null) {
            $result['reference'] = $this->reference;
        }
        if ($this->tag_id !== null) {
            $result['tag_id'] = $this->tag_id;
        }
        if ($this->tag_name !== null) {
            $result['tag_name'] = $this->tag_name;
        }
        if ($this->updated_at !== null) {
            $result['updated_at'] = $this->updated_at;
        }
        return $result;
    }
}

class VmExecLogResponse
{
    /** Returned log entries. */
    public readonly array $entries;
    /** True when the end of file was reached. */
    public readonly bool $eof;
    /** Next byte offset to continue from. */
    public readonly int $next_offset;

    public function __construct(
        array $entries,
        bool $eof,
        int $next_offset,
    ) {
        $this->entries = $entries;
        $this->eof = $eof;
        $this->next_offset = $next_offset;
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data): static
    {
        return new static(
            entries: $data['entries'] ?? null,
            eof: $data['eof'] ?? null,
            next_offset: $data['next_offset'] ?? null,
        );
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        $result = [];
        if ($this->entries !== null) {
            $result['entries'] = $this->entries;
        }
        if ($this->eof !== null) {
            $result['eof'] = $this->eof;
        }
        if ($this->next_offset !== null) {
            $result['next_offset'] = $this->next_offset;
        }
        return $result;
    }
}


// ── Params types for operations with query parameters ───────────────

class ResizeVmDiskParams
{
    /** If true, return an error immediately if the VM is still booting. Default: false */
    public readonly ?bool $skip_wait_boot;

    public function __construct(
        ?bool $skip_wait_boot = null,
    ) {
        $this->skip_wait_boot = $skip_wait_boot;
    }
}

class CreateNewRootVmParams
{
    /** If true, wait for the newly-created VM to finish booting before returning. Default: false. */
    public readonly ?bool $wait_boot;

    public function __construct(
        ?bool $wait_boot = null,
    ) {
        $this->wait_boot = $wait_boot;
    }
}

class VmLogsParams
{
    /** Byte offset into the log file (default: 0) */
    public readonly ?int $offset;
    /** Maximum number of log entries to return */
    public readonly ?int $max_entries;
    /** Filter by 'stdout' or 'stderr' */
    public readonly ?string $stream;

    public function __construct(
        ?int $offset = null,
        ?int $max_entries = null,
        ?string $stream = null,
    ) {
        $this->offset = $offset;
        $this->max_entries = $max_entries;
        $this->stream = $stream;
    }
}

class BranchByRefParams
{
    /** Number of VMs to branch (optional; default 1) */
    public readonly ?int $count;

    public function __construct(
        ?int $count = null,
    ) {
        $this->count = $count;
    }
}

class BranchByTagParams
{
    /** Number of VMs to branch (optional; default 1) */
    public readonly ?int $count;

    public function __construct(
        ?int $count = null,
    ) {
        $this->count = $count;
    }
}

class BranchVmParams
{
    /** If true, keep VM paused after commit. Only applicable when branching a VM ID. */
    public readonly ?bool $keep_paused;
    /** If true, immediately return an error if VM is booting instead of waiting. Only applicable when branching a VM ID. */
    public readonly ?bool $skip_wait_boot;
    /** Number of VMs to branch (optional; default 1) */
    public readonly ?int $count;

    public function __construct(
        ?bool $keep_paused = null,
        ?bool $skip_wait_boot = null,
        ?int $count = null,
    ) {
        $this->keep_paused = $keep_paused;
        $this->skip_wait_boot = $skip_wait_boot;
        $this->count = $count;
    }
}

class UpdateVmStateParams
{
    /** If true, error immediately if the VM is not finished booting. Defaults to false */
    public readonly ?bool $skip_wait_boot;

    public function __construct(
        ?bool $skip_wait_boot = null,
    ) {
        $this->skip_wait_boot = $skip_wait_boot;
    }
}

class DeleteVmParams
{
    /** If true, return an error immediately if the VM is still booting. Default: false */
    public readonly ?bool $skip_wait_boot;

    public function __construct(
        ?bool $skip_wait_boot = null,
    ) {
        $this->skip_wait_boot = $skip_wait_boot;
    }
}

class BranchByVmParams
{
    /** If true, keep VM paused after commit */
    public readonly ?bool $keep_paused;
    /** If true, immediately return an error if VM is booting instead of waiting */
    public readonly ?bool $skip_wait_boot;
    /** Number of VMs to branch (optional; default 1) */
    public readonly ?int $count;

    public function __construct(
        ?bool $keep_paused = null,
        ?bool $skip_wait_boot = null,
        ?int $count = null,
    ) {
        $this->keep_paused = $keep_paused;
        $this->skip_wait_boot = $skip_wait_boot;
        $this->count = $count;
    }
}

class CommitVmParams
{
    /** If true, keep VM paused after commit */
    public readonly ?bool $keep_paused;
    /** If true, return an error immediately if the VM is still booting. Default: false */
    public readonly ?bool $skip_wait_boot;

    public function __construct(
        ?bool $keep_paused = null,
        ?bool $skip_wait_boot = null,
    ) {
        $this->keep_paused = $keep_paused;
        $this->skip_wait_boot = $skip_wait_boot;
    }
}

class ListDomainsParams
{
    /** Filter by VM ID */
    public readonly ?string $vm_id;

    public function __construct(
        ?string $vm_id = null,
    ) {
        $this->vm_id = $vm_id;
    }
}

class ReadFileVmParams
{
    /** Absolute path of the file to read */
    public readonly ?string $path;

    public function __construct(
        ?string $path = null,
    ) {
        $this->path = $path;
    }
}

class BranchByCommitParams
{
    /** Number of VMs to branch (optional; default 1) */
    public readonly ?int $count;

    public function __construct(
        ?int $count = null,
    ) {
        $this->count = $count;
    }
}

